name: Build Android APK - CORRECTED

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK (Fixed)
      uses: android-actions/setup-android@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses >/dev/null 2>&1
        sdkmanager "platforms;android-34" "build-tools;34.0.0"
        
    - name: Install Capacitor
      run: |
        npm install @capacitor/cli@6.0.0 @capacitor/core@6.0.0 @capacitor/android@6.0.0 --no-save
        
    - name: Prepare web files
      run: |
        mkdir -p www
        if [ -f index.html ]; then
          cp index.html www/
          echo "Using index.html"
        elif [ -f client/index.html ]; then
          cp client/index.html www/
          echo "Using client/index.html"
        else
          echo "Creating fallback HTML"
          cat > www/index.html << 'EOF'
        <!DOCTYPE html>
        <html><head><title>Servis Todosijevic</title></head>
        <body><h1>Servis Todosijevic Mobile</h1></body></html>
        EOF
        fi
        ls -la www/
        
    - name: Initialize Capacitor
      run: |
        npx cap init "ServisTodosijevic" com.frigosistem.todosijevic --web-dir=www
        
    - name: Add Android platform
      run: |
        npx cap add android
        
    - name: Sync Capacitor
      run: |
        npx cap sync android
        
    - name: Build APK
      working-directory: ./android
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug --stacktrace --info
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: servis-todosijevic-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30