name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        
    - name: Clean install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install --legacy-peer-deps
        
    - name: Build React app
      run: |
        npm run build
        ls -la dist/
        
    - name: Initialize Capacitor
      run: |
        npx cap init "Servis Todosijevic" com.frigosistem.todosijevic --web-dir=dist
        
    - name: Add Android platform
      run: |
        npx cap add android
        
    - name: Sync Capacitor
      run: |
        npx cap sync android
        
    - name: Build Android APK
      working-directory: ./android
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: servis-todosijevic-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30